accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('perfil/', views.perfil, name='perfil'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path(
        'remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove',
    ),
]

myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('favorite/', include('favorite.urls', namespace='favorite')),
    path('reports/', include('reports.urls', namespace='reports')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('order/<int:order_id>/', views.order_created, name='order_created'),
    path('order/<int:order_id>/invoice/', views.generate_invoice_pdf, name='order_invoice'),
    path('historial-compras/', views.order_history, name='order_history'),
    path('detail/<int:order_id>/', views.order_detail, name='order_detail'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Rol(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()

    def __str__(self):
        return self.nombre

class Usuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rol = models.ForeignKey(Rol, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    
class Perfil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombre_completo = models.CharField(max_length=255)
    telefono = models.CharField(max_length=15)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    direccion = models.CharField(max_length=255)

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Perfil

class AuthenticationForm(forms.Form):
    username = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'placeholder': 'Nombre de usuario', 'class': 'form-control'})
    )
    password = forms.CharField(
        max_length=255,
        widget=forms.PasswordInput(attrs={'placeholder': 'Contraseña', 'class': 'form-control'})
    )


class RegistroForm(UserCreationForm):
    username = forms.CharField(max_length=150, required=True, widget=forms.TextInput(attrs={'placeholder': 'Nombre de usuario'}))
    nombre_completo = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'placeholder': 'Nombre completo'}))
    telefono = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'placeholder': 'Número de teléfono'}))
    fecha_nacimiento = forms.DateField(required=False, widget=forms.DateInput(attrs={'placeholder': 'YYYY-MM-DD'}))
    direccion = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'placeholder': 'Dirección'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Contraseña'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirma tu contraseña'}))


    class Meta:
        model = User
        fields = ('username', 'email', 'nombre_completo', 'telefono', 'fecha_nacimiento', 'direccion', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit)
        if commit:
            user.save()  # Guarda el usuario
            perfil = Perfil(
                user=user,
                nombre_completo=self.cleaned_data['nombre_completo'],
                telefono=self.cleaned_data['telefono'],
                fecha_nacimiento=self.cleaned_data['fecha_nacimiento'],
                direccion=self.cleaned_data['direccion']
            )
            perfil.save()  # Guarda el perfil
        return user
    
    def __init__(self, *args, **kwargs):
        super(RegistroForm, self).__init__(*args, **kwargs)
        self.fields['nombre_completo'].widget.attrs.update({'class': 'mi-clase'})

class EditarPerfilForm(forms.ModelForm):
    username = forms.CharField(max_length=150)

    class Meta:
        model = Perfil
        fields = ('nombre_completo', 'telefono', 'fecha_nacimiento', 'direccion')

    def __init__(self, *args, **kwargs):
        super(EditarPerfilForm, self).__init__(*args, **kwargs)
        self.fields['username'].initial = self.instance.user.username

    def save(self, commit=True):
        user = self.instance.user
        user.username = self.cleaned_data['username']
        user.save()
        return super(EditarPerfilForm, self).save(commit)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from .models import Usuario, Rol, Perfil
from django.urls import reverse
from .forms import RegistroForm, EditarPerfilForm
from django.contrib.auth.decorators import login_required

def register(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            # Guarda el usuario
            user = form.save()
            # Obtiene o crea el rol
            rol, created = Rol.objects.get_or_create(nombre='cliente')
            # Crea el objeto Usuario relacionado
            Usuario.objects.create(user=user, rol=rol)

            # Mensaje de éxito
            messages.success(request, 'Registro exitoso. Ahora puedes iniciar sesión.')
            return redirect('login')
        else:
            # Mensaje de error con detalles de los errores del formulario
            for field in form:
                for error in field.errors:
                    messages.error(request, f"{field.label}: {error}")
            messages.error(request, 'Error al registrar el usuario. Revisa los datos ingresados.')
    else:
        form = RegistroForm()
    return render(request, 'accounts/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                request.session['logged_in'] = True
                return redirect('perfil')
            else:
                messages.error(request, 'Nombre de usuario o contraseña incorrectos')
        else:
            messages.error(request, 'Error al autenticar el usuario')
    else:
        if request.session.get('logged_in'):
            return redirect('tienda')
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    logout(request)
    messages.success(request, 'Sesión cerrada correctamente')
    return redirect('shop:product_list')

def perfil(request):
    request.session['logged_in'] = True
    if request.user.is_superuser:
        return redirect('admin:index')
    try:
        perfil = request.user.perfil
    except Perfil.DoesNotExist:
        perfil = Perfil.objects.create(user=request.user)
    if request.method == 'POST':
        form = EditarPerfilForm(request.POST, instance=perfil)
        print(form)  # Debuggear el formulario
        if form.is_valid():
            form.save()
            return redirect('perfil')
    else:
        form = EditarPerfilForm(instance=perfil)
        print(form)  # Debuggear el formulario
    return render(request, 'accounts/perfil.html', {'form': form, 'perfil': perfil})

@login_required
def editar_perfil(request):
    perfil = request.user.perfil
    if request.method == 'POST':
        form = EditarPerfilForm(request.POST, instance=perfil)
        if form.is_valid():
            form.save()
            return redirect('perfil')
    else:
        form = EditarPerfilForm(instance=perfil)
    return render(request, 'perfil.html', {'form': form})

accounts/templates/accounts/login.html
{% extends 'base_accounts.html' %}
{% load widget_tweaks %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="card mb-5" style="width: 900px; margin: auto; margin-top: 20px;">
        <div class="card-body mx-auto">
            <div class="text-center mb-4">
                <img src="{% static 'img/logo_v_pharma.png' %}" alt="logo" width="150px" class="me-1">
            </div>
            <h2 class="fw-bold text-center" style="color: #4E50B4;">Iniciar sesión</h2>
            <div class="card mt-4" style="width: 500px;">
                <div class="card-body text-center">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group mb-4 text-center ">
                            <p style="color: #4E50B4;">Ingrese su nombre de usuario</p>
                            {{ form.username|add_class:"form-control" }} <!-- Asegúrate de que tenga la clase form-control -->
                            {{ form.username.errors }} 
                        </div>
                        <div class="form-group mb-4 text-center">
                            <p style="color: #4E50B4;">Ingrese su contraseña</p>
                            {{ form.password|add_class:"form-control" }} <!-- Asegúrate de que tenga la clase form-control -->
                            {{ form.password.errors }}
                        </div>
                        <button type="submit" class="btn rounded-pill mb-3 fw-bold" style="background-color: #4E50B4; color: #ffff">Iniciar sesión</button>
                    </form>
                    <div class="mt-3 text-center">
                        <p style="color: #4E50B4;">No tienes cuenta <a href="{% url 'register' %}" style="color: #34DD78;">Regístrate aquí</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/perfil.html
{% extends 'base_accounts_profile.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<style>
  @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap');


  body {
    margin: 0;
    padding: 0;
    font-family: 'Poppins', sans-serif;
  }

  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    font-family: 'Poppins', sans-serif;
  }
  .form-control {
    color: #ccc;
    font-weight: 600;
  }
</style>

<div class="container">
  <div class="row justify-content-center mt-5 mb-5">

    <div class="col">
      <div class="card" style="width: 18rem;">
        <div class="card-body rounded" style="background-color: #9394D5;">
          <div class="d-flex align-items-center mb-4">
            <svg xmlns="http://www.w3.org/2000/svg" width="60" fill="aliceblue" class="bi bi-person-fill"
              viewBox="0 0 16 16">
              <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6" />
            </svg>
            <p style="color: aliceblue; margin-top: 50px;">Hola, {{ user.username }}!</p>
          </div>
          <a href="{% url 'orders:order_history' %}" class="card-link fw-semibold" style="color: aliceblue;">Historial de compra</a>
          <div class="d-flex align-items-center mt-5">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" fill="aliceblue" class="bi bi-box-arrow-in-right"
              viewBox="0 0 16 16">
              <path fill-rule="evenodd"
                d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0z" />
              <path fill-rule="evenodd"
                d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z" />
            </svg>
            <a href="{% url 'logout' %}" style="color: aliceblue; text-decoration: none;" class="ms-1">Cerrar sesión</a>
          </div>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="card" style="width: 50rem; border: none;">
        <div class="card-body rounded" style="background-color: #E7F1F6;">
          <h5 class="card-title fw-bold mb-4" style="color: #4E50B4;">Mi perfil</h5>
          <form method="post">
            {% csrf_token %}
            <div class="form-group mb-3">
                <label for="username" class="fw-semibold" style="color: #4E50B4;">Nombre de Usuario</label>
                <input type="text" class="form-control" id="username" name="username" value="{{ form.username.value }}" placeholder="Ingrese su username">
            </div>
            <div class="form-group mb-3">
                <label for="nombre_completo" class="fw-semibold" style="color: #4E50B4;">Nombre Completo</label>
                <input type="text" class="form-control" id="nombre_completo" name="nombre_completo" value="{{ form.nombre_completo.value }}" placeholder="Ingrese su nombre completo">
            </div>
            <div class="form-group mb-3">
                <label for="telefono" class="fw-semibold"style="color: #4E50B4;">Teléfono</label>
                <input type="text" class="form-control" id="telefono" name="telefono" value="{{ form.telefono.value }}" placeholder="Ingrese su teléfono">
            </div>
            <div class="form-group mb-3">
                <label for="fecha_nacimiento" class="fw-semibold" style="color: #4E50B4;">Fecha de Nacimiento</label>
                <input type="date" class="form-control" id="fecha_nacimiento" name="fecha_nacimiento" value="{{ form.fecha_nacimiento.value }}" placeholder="Ingrese su fecha de nacimiento">
            </div>
            <div class="form-group mb-3">
                <label for="direccion" class="fw-semibold" style="color: #4E50B4;">Dirección</label>
                <input type="text" class="form-control" id="direccion" name="direccion" value="{{ form.direccion.value }}" placeholder="Ingrese su dirección">
            </div>
            <div class="text-center">
              <button type="submit" class="btn rounded" style="color: #E7F1F6; background-color: #4E50B4;">Guardar Cambios</button>
            </div>
        </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base_accounts.html' %}
{% load widget_tweaks %}
{% load static %}

{% block content %}
<div class="container mt-5">
  <div class="card mb-5" style="width: 900px; margin: auto; margin-top: 20px;">
    <div class="card-body mx-auto">
        <div class="text-center mb-4">
          <img src="{% static 'img/logo_v_pharma.png' %}" alt="logo" width="150px" class="me-1">
        </div>
        <h2 class="fw-bold text-center" style="color: #4E50B4;">Registro</h2>
        <div class="card mt-4" style="width: 500px;">
            <div class="card-body text-center">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group m-3">
                      {{ form.username|add_class:"form-control" }}  <!-- Campo de nombre de usuario -->
                      {{ form.username.errors }}
                    </div>
                    <div class="form-group m-3">
                        {{ form.nombre_completo|add_class:"form-control" }}
                        {{ form.nombre_completo.errors }}
                    </div>
                    <div class="form-group m-3">
                        {{ form.telefono|add_class:"form-control" }}
                        {{ form.telefono.errors }}
                    </div>
                    <div class="form-group m-3">
                        {{ form.fecha_nacimiento|add_class:"form-control" }}
                        {{ form.fecha_nacimiento.errors }}
                    </div>
                    <div class="form-group m-3">
                        {{ form.direccion|add_class:"form-control" }}
                        {{ form.direccion.errors }}
                    </div>
                    <div class="form-group m-3">
                        {{ form.password1|add_class:"form-control" }}
                        {{ form.password1.errors }}
                    </div>
                    <div class="form-group m-3">
                        {{ form.password2|add_class:"form-control" }}
                        {{ form.password2.errors }}
                    </div>
                    <button type="submit" class="btn rounded-pill mb-3 fw-bold" style="background-color: #4E50B4; color: #ffff">Registrar</button>
                </form>
            </div>
        </div>
    </div>
</div>
</div>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
{% endif %}
{% endblock %}